spring:
  profiles:
    active: local
    include:
      - jwt
      - oauth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 20
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/color_palette_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yeon
    password: 1234
  sql:
    init:
      mode: never
