spring:
  profiles:
    active: local
    include: jwt
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 20
  redis:
    host: 127.0.0.1
    port: 6379
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never
